# Generated by Django 5.0.4 on 2024-04-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='anount',
            new_name='amount',
        ),
    ]
